# main text of home
name: Smooth Richie
bio: A Girl who travels the world eating noodles

# twitter summary info
description: The website of smooth richie professional saxaphone player

picture: assets/images/picture.jpg

url: http://koppl.in/violet
# your url: http://USERNAME.github.io

# if you don't have any of social below, comment the line
email: smooth.richie@gmail.com

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
